### PR TITLE
Add BoratRAT community threat json and custom .Net DLL for recording audio

### PR DESCRIPTION
**Pull request by 4Nzic-fiddler**
This includes the Scythe threat JSON file, updated README, and the source code and compiled version of AudioRecorder.dll to capture mic audio.

### CODE REVIEW

**Review by 4Nzic-fiddler — COMMENTED** [review]
On line # 298, there's still a typo. AudioRecorder.AudioRecorer should be changed to AudioRecorder.AudioRecorder

**Comment by TheWover** [comment]
Recommend placing the Visual Studio solution/source code in a separate GitHub repository then linking it to the Borat folder structure via a Git submodule. That way, when the entire community-modules repo is zipped up and imported into a SCYTHE instance the Visual Studio files will not be included in that zip and placed on the SCYTHE server.

**Comment by TheWover** [comment]
Recommend that the readme and description explain what the use of Ransomware.dll will do, since that is not apparent from reading the SCYTHE Campaign steps. (What files will be encrypted, how to recover them, algorithms/crypto APIs used, etc.).

**Comment by securepeacock** [comment]
Multiple file paths include C:\Users\Public\Document\ which need to be edited to have C:\Users\Public\Documents\ adding an s to document.

**Comment by 4Nzic-fiddler** [comment]
> Recommend placing the Visual Studio solution/source code in a separate GitHub repository then linking it to the Borat folder structure via a Git submodule. That way, when the entire community-modules repo is zipped up and imported into a SCYTHE instance the Visual Studio files will not be included in that zip and placed on the SCYTHE server.

Done in 5fa1159

**Comment by 4Nzic-fiddler** [comment]
Moved to submodule and deleted source directory from Scythe threat directory

**Pull request merged**
